from Images import Images
from Projects import Projects
from Models import Models


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui(object):
    def setupUi(self, Ui):
        Ui.setObjectName("Ui")
        Ui.resize(900, 700)
        self.centralwidget = QtWidgets.QWidget(Ui)
        self.centralwidget.setObjectName("centralwidget")
        self.boxImage = QtWidgets.QGroupBox(self.centralwidget)
        self.boxImage.setGeometry(QtCore.QRect(10, 190, 371, 451))
        self.boxImage.setObjectName("boxImage")
        self.layoutWidget = QtWidgets.QWidget(self.boxImage)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 20, 121, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.imagesTitle = QtWidgets.QLabel(self.layoutWidget)
        self.imagesTitle.setObjectName("imagesTitle")
        self.verticalLayout_5.addWidget(self.imagesTitle)
        self.images = Images(self.layoutWidget)
        self.images.setMaximumSize(QtCore.QSize(250, 16777215))
        self.images.setObjectName("images")
        self.verticalLayout_5.addWidget(self.images)
        self.layoutWidget1 = QtWidgets.QWidget(self.boxImage)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 23, 121, 421))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.selectFolder = QtWidgets.QPushButton(self.layoutWidget1)
        self.selectFolder.setObjectName("selectFolder")
        self.verticalLayout_3.addWidget(self.selectFolder)
        self.imageBrowser = Images(self.layoutWidget1)
        self.imageBrowser.setMaximumSize(QtCore.QSize(250, 16777215))
        self.imageBrowser.setObjectName("imageBrowser")
        self.verticalLayout_3.addWidget(self.imageBrowser)
        self.addImage = QtWidgets.QPushButton(self.boxImage)
        self.addImage.setGeometry(QtCore.QRect(140, 160, 75, 24))
        self.addImage.setMaximumSize(QtCore.QSize(75, 16777215))
        self.addImage.setObjectName("addImage")
        self.layoutWidget2 = QtWidgets.QWidget(self.boxImage)
        self.layoutWidget2.setGeometry(QtCore.QRect(141, 228, 77, 86))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.removeImage = QtWidgets.QPushButton(self.layoutWidget2)
        self.removeImage.setObjectName("removeImage")
        self.verticalLayout_4.addWidget(self.removeImage)
        self.viewImage = QtWidgets.QPushButton(self.layoutWidget2)
        self.viewImage.setObjectName("viewImage")
        self.verticalLayout_4.addWidget(self.viewImage)
        self.renameImage = QtWidgets.QPushButton(self.layoutWidget2)
        self.renameImage.setObjectName("renameImage")
        self.verticalLayout_4.addWidget(self.renameImage)
        self.boxBug = QtWidgets.QGroupBox(self.centralwidget)
        self.boxBug.setGeometry(QtCore.QRect(380, 190, 491, 451))
        self.boxBug.setObjectName("boxBug")
        self.ImageView = QtWidgets.QGraphicsView(self.boxBug)
        self.ImageView.setGeometry(QtCore.QRect(10, 20, 471, 421))
        self.ImageView.setObjectName("ImageView")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 741, 171))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boxProject = QtWidgets.QGroupBox(self.layoutWidget3)
        self.boxProject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.boxProject.setObjectName("boxProject")
        self.layoutWidget4 = QtWidgets.QWidget(self.boxProject)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 341, 141))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.projects = Projects(self.layoutWidget4, "projects")
        self.projects.setMaximumSize(QtCore.QSize(350, 25))
        self.projects.setObjectName("projects")
        self.verticalLayout.addWidget(self.projects)
        self.NewProject = QtWidgets.QPushButton(self.layoutWidget4)
        self.NewProject.setMaximumSize(QtCore.QSize(350, 25))
        self.NewProject.setObjectName("NewProject")
        self.verticalLayout.addWidget(self.NewProject)
        self.LoadProject = QtWidgets.QPushButton(self.layoutWidget4)
        self.LoadProject.setMaximumSize(QtCore.QSize(350, 25))
        self.LoadProject.setObjectName("LoadProject")
        self.verticalLayout.addWidget(self.LoadProject)
        self.DeleteProject = QtWidgets.QPushButton(self.layoutWidget4)
        self.DeleteProject.setMaximumSize(QtCore.QSize(350, 25))
        self.DeleteProject.setObjectName("DeleteProject")
        self.verticalLayout.addWidget(self.DeleteProject)
        self.horizontalLayout_2.addWidget(self.boxProject)
        self.boxModel = QtWidgets.QGroupBox(self.layoutWidget3)
        self.boxModel.setObjectName("boxModel")
        self.layoutWidget_3 = QtWidgets.QWidget(self.boxModel)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 20, 341, 141))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.models = Models(self.layoutWidget_3, "models")
        self.models.setMaximumSize(QtCore.QSize(350, 25))
        self.models.setObjectName("models")
        self.verticalLayout_2.addWidget(self.models)
        self.NewModel = QtWidgets.QPushButton(self.layoutWidget_3)
        self.NewModel.setMaximumSize(QtCore.QSize(350, 25))
        self.NewModel.setObjectName("NewModel")
        self.verticalLayout_2.addWidget(self.NewModel)
        self.LoadModel = QtWidgets.QPushButton(self.layoutWidget_3)
        self.LoadModel.setMaximumSize(QtCore.QSize(350, 25))
        self.LoadModel.setObjectName("LoadModel")
        self.verticalLayout_2.addWidget(self.LoadModel)
        self.DeleteModel = QtWidgets.QPushButton(self.layoutWidget_3)
        self.DeleteModel.setMaximumSize(QtCore.QSize(350, 25))
        self.DeleteModel.setObjectName("DeleteModel")
        self.verticalLayout_2.addWidget(self.DeleteModel)
        self.horizontalLayout_2.addWidget(self.boxModel)
        self.detectBugsButton = QtWidgets.QPushButton(self.centralwidget)
        self.detectBugsButton.setGeometry(QtCore.QRect(770, 60, 101, 81))
        self.detectBugsButton.setObjectName("detectBugsButton")
        Ui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        Ui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui)
        self.statusbar.setObjectName("statusbar")
        Ui.setStatusBar(self.statusbar)
        self.actionMent_s = QtWidgets.QAction(Ui)
        self.actionMent_s.setObjectName("actionMent_s")

        self.retranslateUi(Ui)
        QtCore.QMetaObject.connectSlotsByName(Ui)

    def retranslateUi(self, Ui):
        _translate = QtCore.QCoreApplication.translate
        Ui.setWindowTitle(_translate("Ui", "BugDetection"))
        self.boxImage.setTitle(_translate("Ui", "Images"))
        self.imagesTitle.setText(_translate("Ui", "Project name"))
        self.selectFolder.setText(_translate("Ui", "Select a Folder"))
        self.addImage.setText(_translate("Ui", "Add"))
        self.removeImage.setText(_translate("Ui", "Remove"))
        self.viewImage.setText(_translate("Ui", "View"))
        self.renameImage.setText(_translate("Ui", "Rename"))
        self.boxBug.setTitle(_translate("Ui", "Detected Bugs"))
        self.boxProject.setTitle(_translate("Ui", "Projects"))
        self.NewProject.setText(_translate("Ui", "New"))
        self.LoadProject.setText(_translate("Ui", "Load"))
        self.DeleteProject.setText(_translate("Ui", "Delete"))
        self.boxModel.setTitle(_translate("Ui", "Models"))
        self.NewModel.setText(_translate("Ui", "New"))
        self.LoadModel.setText(_translate("Ui", "Load"))
        self.DeleteModel.setText(_translate("Ui", "Delete"))
        self.detectBugsButton.setText(_translate("Ui", "DETECT BUGS"))
        self.actionMent_s.setText(_translate("Ui", "Mentés"))
